### ISSUE TITLE
can add a es6 version?

### ISSUE THREAD

**Issue by seenyea** [kirillzyusko/react-native-bundle-splitter#16]
**Is your feature request related to a problem? Please describe.**
Es5 is a long time ago story, now, there lot of project output like a es6 version, can we?

**Comment by kirillzyusko** [comment]
Hi @seenyea 

You mean output in `tsconfig.json`?

I've added it because I wanted to support as much as possible JS engines. However this library has a limitation (it requires at least RN == 0.59, and starting from this version RN has support for latest JSC for Android). So maybe it's really worth to switch to ES6.

Do you think it will be breaking change?

**Comment by seenyea** [comment]
I think we need more example actually:
1. support for es5, es6;
2. naviagtion v3 to v5 demo, especially for gounp way.

everybody, like usage, not really what is it.
can we?

**Comment by seenyea** [comment]
Sometimes, project code is based on es6, but your code is es5, static props will not work well

**Comment by kirillzyusko** [comment]
@seenyea the output code of library es5, that's right. But it should work in es6 and more modern syntax. Static props will not work because of the design of a library itself (you need to do a lazy loading of component, so you can not get an instant access to static members - that's why I've added `static` prop into `register` function). It's not a problem of es5.

**Comment by kirillzyusko** [comment]
Closing this issue as we clarified it's not an ES issue.
