### ISSUE TITLE
Example for How to Use

### ISSUE THREAD

**Issue by Louies89** [kirillzyusko/react-native-bundle-splitter#3]
Hi @kirillzyusko,
Thank you for the library.

I am unable to understand how to use the library.

Can you give a example in the documentation or some example code for different use cases and techniques.

**Comment by kirillzyusko** [comment]
Hi @Louies89 
You can look at https://kirillzyusko.github.io/react-native-bundle-splitter
It's step by step instructions for integration this library into your project
Also you can look at: https://github.com/kirillzyusko/react-native-bundle-splitter-example - it's a basic example how you can use the library
But I'd recommend you look at the documentation (first link)
If you have any questions, please write here
If not - also, please, write here (in this case I can understand, that issue solved and I can close the issue)

**Comment by ClenetTech** [comment]
Hi @kirillzyusko,
Thank you for your reply. Actually later I found the link by searching google.

Actualy the Documentation Link in README.md is not correct, that is why I was unable to navigate from there and put this issue.

Please correct the link in README.md, so that others will not get the same trouble.

Thank You

**Comment by kirillzyusko** [comment]
Oooops
Definetly you are right - link to documentation is wrong. Earlier I did a migration and totally forgot to change the documentation URL in README file.
Thank you for pointing it :)
I updated README file with correct links and pushed new version to npm
