### ISSUE TITLE
Bundle vizualizer still shows files which are excluded from packager/modules.ios

### ISSUE THREAD

**Issue by swizes** [kirillzyusko/react-native-bundle-splitter#36]
**Describe the bug**
My modules.ios.js file does not have src/screens/Test/index.js in it but the bundle visualizer still shows it

**Code snippet**

src/screens/Test/index.js

```
export default register({
  loader: () => import('./TestScreen'),
  group: 'Test',
});
```
I don't preload anything yet, those stuffs are still visible in bundle visualizer.

**Expected behavior**
The src/screens/Test and src/screens/Empty should not be in initial bundle, they should have been loaded afterwards when I want them to be loaded

**Screenshots**

![image](https://user-images.githubusercontent.com/8876645/160084083-c8557a34-6887-47ee-9208-4cff975bf5c3.png)

**Comment by kirillzyusko** [comment]
Hi @swizes 

Even if you use `bundle-vizualizer` - "lazy" files will be shown there. That's how RAM bundles works - these files are not excluded from main bundle. The structure of RAM bundles will allow to load them lazily, but they are not moving to a new JS bundle 🤷‍♂️ 

If you want to check, that lazy mode really works, then I would recommend you to check the output of `investigate` function. Just add these lines of the code to `index.js`:

```js
import { investigate } from 'react-native-bundle-splitter/dist/utils';

console.log(`module.exports = ${JSON.stringify(investigate().loaded.sort())};`);
```

It will show you a list of files, which will be loaded on the start of the application. (see [this](https://kirillzyusko.github.io/react-native-bundle-splitter/docs/metro) - I recommend to update packager info at least **two** times to get a valid list of loaded modules. It seems like a first time (when you don't have a pre-configured list) it calculates file list a little bit incorrectly, but once you've updated it and restarted metro with `reset-cache` option - it should produce a real list of modules).

Thus you will understand, which files are excluded.

Let me know, if you have any other questions!

**Comment by swizes** [comment]
> Hi @swizes
> 
> Even if you use `bundle-vizualizer` - "lazy" files will be shown there. That's how RAM bundles works - these files are not excluded from main bundle. The structure of RAM bundles will allow to load them lazily, but they are not moving to a new JS bundle 🤷‍♂️
> 
> If you want to check, that lazy mode really works, then I would recommend you to check the output of `investigate` function. Just add these lines of the code to `index.js`:
> 
> ```js
> import { investigate } from 'react-native-bundle-splitter/dist/utils';
> 
> console.log(`module.exports = ${JSON.stringify(investigate().loaded.sort())};`);
> ```
> 
> It will show you a list of files, which will be loaded on the start of the application. (see [this](https://kirillzyusko.github.io/react-native-bundle-splitter/docs/metro) - I recommend to update packager info at least **two** times to get a valid list of loaded modules. It seems like a first time (when you don't have a pre-configured list) it calculates file list a little bit incorrectly, but once you've updated it and restarted metro with `reset-cache` option - it should produce a real list of modules).
> 
> Thus you will understand, which files are excluded.
> 
> Let me know, if you have any other questions!

I realized that the second call show final state. Now I have understood the logic behind it. Thanks

I do have another question

I am not sure if it is possible to make the scenario but 

In which cases the application won't open the screen, when it is not added into modules.android.js or not lazy loaded.

I have tried to break the aplication by not loading the screen file but it was always possible to navigate to the screen.

**Comment by kirillzyusko** [comment]
> I do have another question
> I am not sure if it is possible to make the scenario but
> In which cases the application won't open the screen, when it is not added into modules.android.js or not lazy loaded.
> I have tried to crash the aplication by not loading the screen file but it was always possible to navigate to the screen.

@swizes I'm not sure I get the question...

If your `packager` folder content will be desynchronized (i. e. not include some files, which are needed), then it will have a reverse effect - the startup time will be increased, because it will evaluate initial bundle and load other files, which are not listed in the packager. And it will be always slower (at least we have verified it using a slow emulator in CI and executed performance tests using `react-native-performance`).

If your packager folder will be synchronized, but you don't use `preload` API, then on low-end devices user may see blank screen before the actual content of the screen (it's also up to how much files will be needed to evaluate for a particular screen).

I think it's really hard to get a crash, if you don't update the `packager`. Though it may be a case, but it will be revealed only in release builds, since on debug builds it will simply download necessary content from `Metro` bundler.

I hope I answered, but if you have any other questions - feel free to ask

**Comment by swizes** [comment]
Thanks for the answers. 

If I am using hermes on iOS too, do i need to enable ram bundle in the iOS project or the same argument about hermes on android is also valid for iOS (I guess so)

**Comment by swizes** [comment]
@kirillzyusko 


Thanks for the answers. 

If I am using hermes on iOS too, do i need to enable ram bundle in the iOS project or the same argument about hermes on android is also valid for iOS (I guess so)

**Comment by kirillzyusko** [comment]
@swizes I think you don't need to enable RAM format on iOS, since Hermes by default will load only necessary parts of JS bundle. And as far as I know RAM format has conflicts with Hermes and JS engine can not execute the script in this format correctly.

Though you can try to check it and see whether it crashes app or not 🙂 I haven't used Hermes on iOS so can not be 100% sure, ha-ha 😅
