### ISSUE TITLE
Is this library relevant if already using Hermes on Android?

### ISSUE THREAD

**Issue by ninjz** [kirillzyusko/react-native-bundle-splitter#70]
I know that if you are using Hermes, you don't need to enable RAM bundles. But I want to know if using this is an additional optimization on top of using Hermes as I've heard that code-splitting is recommended on top of having Hermes enabled.

Is this library useful on top of having Hermes enabled on Android?

**Comment by kirillzyusko** [comment]
> Is this library useful on top of having Hermes enabled on Android?

Definitely, yes.

This library is an abstraction concept of code-splitting and it can work with any code splitting low-level primitives, i. e.:
- RAM bundles (which are deprecated now)
- Hermes lazy-code evaluation
- Webpack lazy loading.

The main advantage of this library is an ability to `preload` components/routes on demand (i. e. along with HTTP request that makes `/login` request), thus reducing an overall time of spinner time and reducing blinking/freezes (typically happens when content/component is not loaded, but you mount it anyway).

I hope I answered on the question, so I'll close that issue, but if you get any other questions - feel free to ask them!

**Comment by ninjz** [comment]
@kirillzyusko thanks for the response.

I think what I'm confused about is what the docs say [here](https://kirillzyusko.github.io/react-native-bundle-splitter/docs/fundamentals/enabling-ram-bundle#android):
> If you are trying to enable this feature with Hermes engine, you may faced with application crash. It's a known [issue](https://github.com/facebook/react-native/issues/25730). As a temporary solution you can don't activate this bundle format for Android, since Hermes is using similar [mechanism](https://github.com/facebook/react-native/issues/25730#issuecomment-514115115).

Just want to double check before I invest my time into integrating this: 
1. This will work on Android if I skip the step of enabling Ram bundles and use Hermes?
2. This will work with Indexed Ram Bundles on iOS with Hermes enabled?

**Comment by kirillzyusko** [comment]
> This will work on Android if I skip the step of enabling Ram bundles and use Hermes?

Yes, since Hermes loads bundle lazily by default.

> This will work with Indexed Ram Bundles on iOS with Hermes enabled?

Most likely no and you will get a crash 🙂 If you are using Hermes then you can skip a section with activating RAM bundles, because RAM bundles are necessary for JSC. Hermes uses its own format, so no extra actions are required - it should work out-of-the-box.

Thank you for the issue, I think I will need to re-work this piece in documentation!

**Comment by kirillzyusko** [comment]
I updated docs in https://github.com/kirillzyusko/react-native-bundle-splitter/pull/71

I hope now it's clearer when and what you should change in the project. If you get any questions or have any suggestions on what can be improved - feel free to leave your comments here 😊

**Comment by ninjz** [comment]
Thanks for the clarification @kirillzyusko. Looking forward to giving this package a spin!
